language: python

sudo: false

python:
  - "3.6"

install:
  - pip install --no-cache-dir -r requirements.txt
  - pip install git+https://github.com/iobis/pyxylookup.git#egg=pyxylookup

script:
  - nosetests -v --with-coverage --cover-package=service

after_success:
  - coveralls --verbose
